package FrontEnd;

import BackEnd.Parque;
import BackEnd.Sistema;
import BackEnd.TipoParque;
import Serializacao.Serializacao;
import javax.swing.JOptionPane;

public class JanelaAdmParquesAdd extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao dados;
    
    public JanelaAdmParquesAdd(Sistema sistema, Serializacao dados) {
        initComponents();
        this.sistema = sistema;
        this.dados = dados;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        verTipos();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        
    }
    
    private void verTipos() {
        TipoParque[]tipos = {TipoParque.CONDICIONADO, TipoParque.LIVRE, TipoParque.LUGAR_ASSEGURADO};
        for (TipoParque tipo : tipos) {
            comboTipos.addItem(tipo.toString());
        }
        
        /*  
        jComboBox1.addItem(TipoParque.CONDICIONADO.toString());
        jComboBox1.addItem(TipoParque.LIVRE.toString());
        jComboBox1.addItem(TipoParque.LUGAR_ASSEGURADO.toString());
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNumLugares = new javax.swing.JTextField();
        comboTipos = new javax.swing.JComboBox<>();
        txtCodigo1 = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnVoltar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(246, 246, 246));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Selecione o tipo de parque");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 210, 40));

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Adicionar Parque");
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 276, 51));

        jLabel21.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Nome");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 110, 70, 31));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel8.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 263, 40));

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Nº máximo de lugares");
        jLabel22.setToolTipText("");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 210, 190, 31));

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Código");
        jLabel23.setToolTipText("");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 160, 80, 31));

        txtNumLugares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumLugaresActionPerformed(evt);
            }
        });
        jPanel8.add(txtNumLugares, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 263, 40));

        comboTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo de parque..." }));
        comboTipos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        comboTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiposActionPerformed(evt);
            }
        });
        jPanel8.add(comboTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 260, 40));

        txtCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo1ActionPerformed(evt);
            }
        });
        jPanel8.add(txtCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 263, 40));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 510, 460));

        btnVoltar.setBackground(new java.awt.Color(153, 153, 153));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar.setText("Adicionar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 110, 40));

        btnVoltar1.setBackground(new java.awt.Color(153, 153, 153));
        btnVoltar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar1.setText("Voltar");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNumLugaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumLugaresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumLugaresActionPerformed

    private void comboTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiposActionPerformed
        
    }//GEN-LAST:event_comboTiposActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza O nome do parque");
            txtNome.requestFocus();
            return;
        }
        if (txtCodigo1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza O codigo do parque");
            txtCodigo1.requestFocus();
            return;
        }
        if (txtNumLugares.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza O numero maximo de lugares do parque");
            txtNumLugares.requestFocus();
            return;
        }
        if (comboTipos.getSelectedItem().toString().equalsIgnoreCase("Selecione o tipo de parque...")) {
            JOptionPane.showMessageDialog(this, "Selecione um tipo");
            return;
        }
        TipoParque tipo;
        if (comboTipos.getSelectedItem().toString().equalsIgnoreCase("LIVRE")) {
            tipo = TipoParque.LIVRE;
        } else if (comboTipos.getSelectedItem().toString().equalsIgnoreCase("CONDICIONADO")) {
            tipo = TipoParque.CONDICIONADO;
        } else {
            tipo = TipoParque.LUGAR_ASSEGURADO;
        }
        Parque parque = new Parque (tipo, txtNome.getText(), Integer.parseInt(txtNumLugares.getText()), txtCodigo1.getText());
        sistema.getListaParques().registarParque(parque);
        dados.guardar(sistema);
        JOptionPane.showMessageDialog(this, "Parque criado com sucesso!");
        txtNome.setText("");
        txtCodigo1.setText("");
        txtNumLugares.setText("");
        comboTipos.setSelectedItem("Selecione o tipo de parque...");
        dispose();
        JanelaAdmParques j = new JanelaAdmParques(sistema, dados);
        j.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        dispose();
        JanelaAdm janela = new JanelaAdm(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void txtCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo1ActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btnVoltar1;
    private javax.swing.JComboBox<String> comboTipos;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtCodigo1;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumLugares;
    // End of variables declaration//GEN-END:variables
}
